version: '3.8'
services:
  postgres-db:
    image: postgres:15-alpine
    container_name: marketplace-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ecommerce_TMN_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis-cache:
    image: redis:7-alpine
    container_name: marketplace-redis
    ports:
      - "6379:6379"

volumes:
  pgdata: